/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class I2cNative */

#ifndef _Included_I2cNative
#define _Included_I2cNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     I2cNative
 * Method:    openBus
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_I2cNative_openBus
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     I2cNative
 * Method:    closeBus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_I2cNative_closeBus
  (JNIEnv *, jclass, jint);

/*
 * Class:     I2cNative
 * Method:    writeByte
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_I2cNative_writeByte
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     I2cNative
 * Method:    writeWord
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_I2cNative_writeWord
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     I2cNative
 * Method:    readWord
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_I2cNative_readWord
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     I2cNative
 * Method:    readAllBytes
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_I2cNative_readAllBytes
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
